### ISSUE TITLE
Use docker volumes for registry mounts

### ISSUE THREAD

**Issue by willseward** [sshipway/rancher-catalogue#7]
It would be nice to be able to specify the volumes individually in the registry template. That way it would be possible to use it with convoy. At the moment, the forward slashes get in the way.

**Comment by sshipway** [comment]
The problem here is that we get constrained by the limitations of the templating language.  As yet, there is no way to do conditionals and so it makes it difficult to support both Convoy and filesystem mounts without having a huge number of variables.

For convoy to work, we'd need a single mount (or a set of mounts with a common prefix?) and refer to subdirectories under that.  I'll need to look into it once I get the free time.

**Comment by willseward** [comment]
I appreciate that.

My suggestion would be to have REG_DIR, CERTS_DIR, DB_DIR, and PROXY_DIR. That way someone with an existing implementation would not be left out in the cold, and you could specify named volumes if needed. 

That does complicate things though. I agree with the need for conditionals.

**Comment by sshipway** [comment]
A separate template has now been created ( registry-convoy ) that does this.
